---
title: "Untitled"
author: "Jen Ren"
date: "6/4/2020"
output: html_document
---

```{r}
library(googlesheets4)
library(httr)
library(jsonlite)
library(tidyverse)
```

```{r}
dataset_url <- "https://docs.google.com/spreadsheets/u/1/d/1mTthE5lwqVnTCIm3iQtQXLyxwK-pc17cuCp--BhAYX8/htmlview?fbclid=IwAR0Ue3318iT4__1oVicUWBNef9gNiw7JDzJRq7M1GNnh_h5i2GQ9kYl_n1U#"
```

```{r}
dataset <- read_sheet(dataset_url, skip = 3) %>% 
  rename_all(tolower)

View(dataset)
```

Define a function for looking up a place:

```{r}
has_key <- !identical(Sys.getenv("GOOGLE_MAPS_API_KEY"), "")

if (!has_key) {
  message("No Google Maps API key found; code chunks will not be run")
}

get_place_id <- function(name, city, api_key = Sys.getenv("GOOGLE_MAPS_API_KEY")) {
  input <- str_c(name, city, sep = " ")
  r <- GET(
    url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json",
    query = list(
      key = api_key,
      input = input,
      inputtype = "textquery"
    )
  )
  content(r, "parsed")
}
```


```{r}
get_place_id("Alchemy Coffee Collective", "Berkeley")
```

```{r}
dataset_sample <- dataset %>% top_n(10, name)

dataset_sample_lookup <- dataset_sample %>% 
  mutate(json = map2(name, location, get_place_id))

dataset_sample_lookup %>% View()
```


```{r}
dataset_sample_place_id <- dataset_sample_lookup %>% 
  unnest_wider(json) %>% 
  hoist(
    candidates, 
    place_id = list(1, "place_id")
  )

dataset_sample_place_id %>% View()
```

```{r}
get_place_details <- function(place_id, api_key = Sys.getenv("GOOGLE_MAPS_API_KEY")) {
  r <- GET(
    "https://maps.googleapis.com/maps/api/place/details/json",
    query = list(
      key = API_KEY,
      place_id = place_id,
      fields = "address_component,formatted_address,geometry,business_status,url,formatted_phone_number,opening_hours,website"
    )
  )
  content(r, "parsed")
}
```

```{r}
dataset_sample_place_id %>% 
  mutate(json = map(place_id, get_place_details)) %>% 
  hoist(
    json,
    hours_gmaps = list("result", "opening_hours", "weekday_text"),
    address_gmaps = list("result", "formatted_address"),
    status_gmaps = list("result", "business_status"),
    lat_gmaps = list("result", "geometry", "location", "lat"),
    lng_gmaps = list("result", "geometry", "location", "lng"),
    phone_gmaps = list("result", "formatted_phone_number"),
    website_gmaps = list("result", "website"),
    gmaps_url = list("result", "url")
  ) %>% 
  View()
```



## Making it work for one:

```{r}
r_lookup <- GET(
  "https://maps.googleapis.com/maps/api/place/findplacefromtext/json",
  query = list(
    key = API_KEY,
    input = "Alchemy Collective Cafe Berkeley",
    inputtype = "textquery"
  )
)
```

```{r}
content(r, "parsed")
```

```{r}
r_details <- GET(
  "https://maps.googleapis.com/maps/api/place/details/json",
  query = list(
    key = API_KEY,
    place_id = "ChIJCeoIuHt-hYAR0OZUwj2Gqxk",
    fields = "address_component,formatted_address,geometry,business_status,url,formatted_phone_number,opening_hours,website"
  )
)
```

```{r}
View(content(r_details, "parsed"))
```

```{r}
hours_list <- content(r_details, "parsed")$result$opening_hours$weekday_text
hours <- paste(hours_list, collapse = "\n")
```

```{r}
content(r_details, "parsed")$result$address_components
```

```{r}
content(r_details, "parsed")$result$address_components[8]
```

```{r}
addr_components <- content(r_details, "parsed")$result$address_components
```

```{r}
tibble(addr_components) %>% 
  hoist(
    addr_components,
    zipcode = c("types", "postal_code")
  ) %>% 
  View()
```

